aliases:
  use:
    leaflet:
      value: ./renderers/leaflet.mjs,
      description: Leaflet is the leading open-source JavaScript library for mobile-friendly interactive maps. It has all the mapping features most developers ever need.
    maplibre:
      value: ./renderers/maplibre.mjs,
      description: MapLibre GL JS is a TypeScript library that uses WebGL to render interactive maps from vector tiles in a browser. The customization of the map comply with the MapLibre Style Spec.
    openlayers:
      value: ./renderers/openlayers.mjs,
      description: OpenLayers makes it easy to put a dynamic map in any web page. It can display map tiles, vector data and markers loaded from any source. OpenLayers has been developed to further the use of geographic information of all kinds.
  width:
    Half: 50%
    Full: 100%
  height:
    Half: 50vh
    Full: 100vh
  center:
    ARGENTINA Buenos Aires: [ -58.3816, -34.6037 ]
    BANGLADESH Dhaka: [ 90.4125, 23.8103 ]
    BRAZIL Sao Paulo: [ -46.6333, -23.5505 ]
    CHINA Beijing: [ 116.4074, 39.9042 ]
    CHINA Shanghai: [ 121.4737, 31.2304 ]
    EGYPT Cairo: [ 31.2357, 30.0444 ]
    INDIA Delhi: [ 77.1025, 28.7041 ]
    INDIA Mumbai: [ 72.8777, 19.0760 ]
    JAPAN Osaka: [ 135.5022, 34.6937 ]
    MEXICO Mexico City: [ -99.1332, 19.4326 ]
    NIGERIA Lagos: [ 3.3792, 6.5244 ]
    PAKISTAN Karachi: [ 67.0011, 24.8607 ]
    PILLIPPINES Manila: [ 120.9842, 14.5995 ]
    TAIWAN Changhua County: [120.5445, 24.0756]
    TAIWAN Hsinchu County: [121.0128, 24.8267]
    TAIWAN Hualien County: [121.6112, 23.9911]
    TAIWAN Kaohsiung City: [120.2667, 22.6333]
    TAIWAN Keelung City: [121.741, 25.131]
    TAIWAN Miaoli County: [120.8152, 24.5734]
    TAIWAN Nantou County: [120.9818101, 23.9512034]
    TAIWAN New Taipei City: [121.457, 25.062]
    TAIWAN Penghu County: [119.5825, 23.5767]
    TAIWAN Pingtung County: [120.5502695, 22.5468588]
    TAIWAN Taichung City: [120.6736, 24.1477]
    TAIWAN Tainan City: [120.2067478, 22.9963617]
    TAIWAN Taipei City: [121.5182451, 25.0504781]
    TAIWAN Taitung County: [121.1508031, 22.7706117]
    TAIWAN Taoyuan City: [121.297, 24.994]
    TAIWAN Yilan County: [121.7627819, 24.7637321]
    TURKEY Istanbul: [ 28.9784, 41.0082 ]
    USA New York City: [ -74.0059, 40.7128 ]
  zoom:
    Whole world: 0
    Subcontinental area: 2
    Large African country: 5
    Large European country: 6
    Wide area, large metropolitan area: 9
    Metropolitan area: 10
    City: 11
    Town, or city district: 12
    Village, or suburb: 13
    Street: 16
    Block, park, addresses: 17
    Building: 20
  XYZ:
    OSM Carto: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    OSM Bright: https://tile.openstreetmap.jp/styles/osm-bright/512/{z}/{x}/{y}.png
    MapTiler Basic: https://tile.openstreetmap.jp/styles/maptiler-basic-en/512/{z}/{x}/{y}.png
    MapTiler Toner: https://tile.openstreetmap.jp/styles/maptiler-toner-ja/512/{z}/{x}/{y}.png
    OpenMapTiles: https://tile.openstreetmap.jp/styles/openmaptiles/512/{z}/{x}/{y}.png
    TAIWAN Rudymap: https://tile.happyman.idv.tw/map/moi_osm/{z}/{x}/{y}.png
    TAIWAN Happyman GPX: https://tile.happyman.idv.tw/map/gpxtrack/{z}/{x}/{y}.png
    TAIWAN Happyman MOI: https://tile.happyman.idv.tw/map/moi_osm/{z}/{x}/{y}.png
    TAIWAN NLSC AERIAL: https://wmts.nlsc.gov.tw/wmts/PHOTO2/default/GoogleMapsCompatible/{z}/{y}/{x}
    TAIWAN NLSC TOPO: https://wmts.nlsc.gov.tw/wmts/PHOTO_MIX/default/GoogleMapsCompatible/{z}/{y}/{x}
    TAIWAN TERRAIN-RGB:   https://osmhacktw.github.io/terrain-rgb/tiles/{z}/{x}/{y}.png
  WMTS:
    TAIWAN NLSC: https://wmts.nlsc.gov.tw/wmts
    TAIWAN TERRAIN-RGB: https://osmhacktw.github.io/terrain-rgb/wmts.xml
    TAIWAN TAIPEI-GOV: https://www.historygis.udd.gov.taipei/wmts
    TAIWAN SINICA: https://gis.sinica.edu.tw/tileserver/wmts
    TAIWAN SINICA_TAOYUAN: https://gis.sinica.edu.tw/taoyuan/wmts
    TAIWAN SINICA_TAICHUNG:  https://gis.sinica.edu.tw/taichung/wmts
    TAIWAN SINICA_CHIAYI:  https://gis.sinica.edu.tw/chiayi/wmts
    TAIWAN SINICA_HUALIAN:  https://gis.sinica.edu.tw/hualien/wmts
    TAIWAN SINICA_SHANGHAI: http://gis.sinica.edu.tw/shanghai/wmts
    TAIWAN SINICA_BEIJING:  http://gis.sinica.edu.tw/beijing/wmts
    TAIWAN SINICA_WORLD: https://gis.sinica.edu.tw/worldmap/wmts-proxy
    TAIWAN SINICA_CCTS:  https://gis.sinica.edu.tw/ccts/wmts
    TAIWAN NCU_REMOTE:  https://data.csrsr.ncu.edu.tw/SP/wmts
    TAIWAN NCU_REMOTE_TW: https://data.csrsr.ncu.edu.tw/SP_TW_FC/wmts
    TAIWAN CHIAYI-GOV: https://3dmap.chiayi.gov.tw/wmts/
